[build]
  publish = "public"
  command = "hugo"
  
[context.production.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[[redirects]]
  from = "https://jamesphare.org/blog"
  to = "https://jamesphare.org/"
  status = 301
  force = true
  query = {id = ":id"}