[build]
  publish = "public"
  command = "hugo"
  
[context.production.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[[redirects]]
  from = "/blog"
  to = "/"
  status = 301
  force = false
  query = {path = ":path"}